#!/usr/bin/env python3
"""
Generate oracle test vectors from the authoritative reference implementations:
  - `packbits` PyPI package (0.6)          -> PackBits compression oracle
  - treideme/brother_pt `cmd.py` functions -> command-stream oracle

These are the SAME libraries brother_pt drives real PT-P710BT hardware with, so
matching their bytes is equivalent to matching the wire protocol (minus USB).

Writes a C header `oracle_generated.h` consumed by test_ptouch.c.

Usage:
  python3 gen_oracle.py <path-to-brother_pt-repo> <out header>
"""
import sys
import os
import importlib.util


def load_cmd_module(brother_pt_repo):
    """Import brother_pt/cmd.py in isolation (it only needs `packbits`)."""
    cmd_path = os.path.join(brother_pt_repo, "brother_pt", "cmd.py")
    spec = importlib.util.spec_from_file_location("bpt_cmd", cmd_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def c_bytes(name, data):
    body = ", ".join("0x%02X" % b for b in data)
    return ("static const unsigned char %s[] = { %s };\n"
            "static const unsigned int %s_len = %d;\n" % (name, body, name, len(data)))


def main():
    brother_pt_repo = sys.argv[1]
    out_path = sys.argv[2]

    import packbits
    cmd = load_cmd_module(brother_pt_repo)

    lines = []
    lines.append("/* AUTO-GENERATED by gen_oracle.py — do not edit. */\n")
    lines.append("/* Oracle: packbits 0.6 + treideme/brother_pt cmd.py */\n")
    lines.append("#ifndef ORACLE_GENERATED_H\n#define ORACLE_GENERATED_H\n\n")

    # --- PackBits vectors -------------------------------------------------
    # Canonical inputs incl. classic Apple/TIFF test vector and raster-like data.
    pb_inputs = {
        # Classic Wikipedia/TIFF PackBits example.
        "pb_classic": bytes([0xAA, 0xAA, 0xAA, 0x80, 0x00, 0x2A, 0xAA, 0xAA,
                             0xAA, 0xAA, 0x80, 0x00, 0x2A, 0x22, 0xAA, 0xAA,
                             0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA]),
        "pb_all_ff":   bytes([0xFF] * 16),
        "pb_all_00":   bytes([0x00] * 16),
        "pb_single":   bytes([0x5A]),
        "pb_two_same": bytes([0x42, 0x42]),
        "pb_alt":      bytes([0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF]),
        "pb_raster1":  bytes([0x00, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x81, 0x00,
                              0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00]),
        "pb_run129":   bytes([0x7E] * 129),   # crosses the 128-run boundary
        "pb_empty":    bytes([]),
    }
    for name, data in pb_inputs.items():
        enc = packbits.encode(data)
        lines.append(c_bytes("%s_in" % name, data))
        lines.append(c_bytes("%s_enc" % name, enc))
        lines.append("\n")

    # --- Full command-stream oracle for a tiny bitmap ---------------------
    # Build the print-job output byte stream exactly as brother_pt would emit it
    # (order per printer.py: update_status writes then print_data writes),
    # for 24mm tape and a 3-line raster where line 1 is empty.
    media_width_mm = 24
    # 3 raster lines, 16 bytes each (already bit-packed, as gen_raster_commands expects).
    raster = bytearray()
    raster += bytes([0x00] * 16)                                  # empty -> 'Z'
    raster += bytes([0xFF, 0x00] * 8)                             # pattern -> 'G'
    raster += bytes([0x00, 0x00, 0xFF, 0xFF] + [0x00] * 12)       # pattern -> 'G'
    raster = bytes(raster)
    num_lines = len(raster) // cmd.LINE_LENGTH_BYTES

    stream = bytearray()
    # update_status() output side
    stream += cmd.invalidate()
    stream += cmd.initialize()
    stream += cmd.status_information_request()
    # print_data() output side
    stream += cmd.enter_dynamic_command_mode()
    stream += cmd.enable_status_notification()
    stream += cmd.print_information(raster, media_width_mm)
    stream += cmd.set_mode()               # default AUTO_CUT
    stream += cmd.set_advanced_mode()      # 0x08 no-chain
    stream += cmd.margin_amount(0)
    stream += cmd.set_compression_mode()
    for c in cmd.gen_raster_commands(raster):
        stream += c
    stream += cmd.print_with_feeding()

    lines.append("/* Full print-job stream: 24mm, 3 raster lines (line 0 empty). */\n")
    lines.append("static const unsigned char oracle_stream_media_width = %d;\n" % media_width_mm)
    lines.append("static const unsigned int  oracle_stream_num_lines = %d;\n" % num_lines)
    lines.append(c_bytes("oracle_raster", raster))
    lines.append(c_bytes("oracle_stream", bytes(stream)))
    lines.append("\n#endif /* ORACLE_GENERATED_H */\n")

    with open(out_path, "w") as f:
        f.writelines(lines)

    print("wrote %s (%d bytes stream, %d packbits vectors)" %
          (out_path, len(stream), len(pb_inputs)))


if __name__ == "__main__":
    main()
